# Generated by Django 4.0.3 on 2022-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='hello', max_length=255, verbose_name='username'),
            preserve_default=False,
        ),
    ]
