# Generated by Django 4.0.3 on 2022-03-11 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0002_auto_20220311_1008'),
        ('custom_auth', '0002_user_preferred_currency_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_coins',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to='coin.coin'),
        ),
    ]
