version: "3"

services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
  web:
    build: .
    command: bash -c "python WalletPy/manage.py migrate coin && python WalletPy/manage.py migrate && python WalletPy/manage.py runserver 0.0.0.0:8080 --insecure"
    environment:
      - MYSQL_ROOT_PASSWORD=mariadb
      - MYSQL_DATABASE=mariadb
      - MYSQL_USER=mariadb
      - MYSQL_PASSWORD=mariadb
      - MYSQL_HOST=db
    volumes:
      - .:/code
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  mariadb_data:
