# Generated by Django 4.0.3 on 2022-03-11 10:08

from django.db import migrations


DEFAULT_COINS = (
    ('ethereum', 'ETH'),
    ('bitcoin', 'BTC'),
    ('litecoin', 'LTC'),
    ('chainlink', 'LINK'),
    ('ripple', 'XRP'),
    ('solana', 'SOL'),
    ('cardano', 'ADA'),
    ('polkadot', 'DOT')
)

def add_coin(apps, schema_editor):
    Coin = apps.get_model('coin', 'Coin')
    for name, symbol in DEFAULT_COINS:
        coin = Coin(name=name,symbol=symbol)
        coin.save()
            
class Migration(migrations.Migration):

    dependencies = [
        ('coin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_coin),
    ]
